services:
  mongo:
    image: mongo:latest
    container_name: loyalty-mongo-prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: GevPass12
    ports:
      - "27017:27017"
    volumes:
      - mongodb_prod_data:/data/db
    networks:
      - loyalty-prod
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: loyalty-backend-prod
    ports:
      - "8000:8000"
    env_file:
      - env.prod
    environment:
      - NODE_ENV=production
      - PORT=8000
      - MONGO_URI=mongodb://admin:GevPass12@mongo:27017/loyalty-prod-db?authSource=admin
      - BACKEND_URL=https://your-domain.com
      - FRONTEND_URL=https://your-domain.com
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - loyalty-prod
    depends_on:
      - mongo
    restart: unless-stopped
    command: sh -c "npm run init-bars && npm start"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: loyalty-frontend-prod
    ports:
      - "3000:3000"
    env_file:
      - env.prod
    environment:
      - REACT_APP_API_URL=https://your-domain.com/api
      - REACT_APP_TELEGRAM_BOT_NAME=Loyalty_bot
      - REACT_APP_USE_MOCK_AUTH=false
    networks:
      - loyalty-prod
    depends_on:
      - backend
    restart: unless-stopped

networks:
  loyalty-prod:
    driver: bridge

volumes:
  mongodb_prod_data: 