services:
  mongo:
    image: mongo:latest
    container_name: loyalty-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: GevPass12
    volumes:
      - mongodb_data:/data/db
    networks:
      - web
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: loyalty-frontend
    ports:
      - "3001:3000"    
    environment:
      - REACT_APP_API_URL=http://localhost:8001/api
      - REACT_APP_TELEGRAM_BOT_NAME=orrders_food_bot
      - NODE_ENV=development
      - REACT_APP_USE_MOCK_AUTH=true
    volumes:
      - ./frontend:/app
      - node_modules_volume:/app/node_modules
    networks:
      - web
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: loyalty-backend
    ports:
      - "8001:8000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://admin:GevPass12@mongo:27017/loyalty-db?authSource=admin
    networks:
      - web
    restart: unless-stopped

networks:
  web:
volumes:
  mongodb_data:
  node_modules_volume:  
