# Dockerfile для разработки
FROM node:18-alpine

# Рабочая директория внутри контейнера
WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Копируем весь остальной код
COPY . .

# Открываем порт
EXPOSE 3000

# Запускаем в режиме разработки
CMD ["npm", "start"] 